services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "rm -f tmp/pids/server.pid && ./bin/rails server -b 0.0.0.0"
    environment:
      RAILS_ENV: development
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"

  vite:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec vite dev
    environment:
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3036:3036"

  sidekiq:
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    environment:
      RAILS_ENV: development
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  elasticsearch:
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m

volumes:
  bundle_cache:
  node_modules:
  