default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

development:
  <<: *default
  database: fotmob_clone_development

test:
  <<: *default
  database: fotmob_clone_test

production:
  <<: *default
  database: fotmob_clone_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  