sync_static_data:
  cron: '0 3 * * 1'
  class: SyncStaticDataWorker
  queue: low
  description: 'Sync countries and leagues weekly'

sync_matches:
  cron: '0 6 * * *'
  class: SyncMatchesWorker
  queue: default
  description: 'Sync today matches at 6am'

sync_live_matches:
  cron: '*/2 * * * *'
  class: SyncLiveMatchesWorker
  queue: critical
  description: 'Sync live matches every 2 minutes'

sync_match_details:
  cron: '*/30 * * * *'
  class: SyncMatchDetailsWorker
  queue: default
  description: 'Sync live match events, stats, lineups every 30 minutes'

sync_highlights:
  cron: '0 23 * * *'
  class: SyncHighlightsWorker
  queue: low
  description: 'Sync match highlights every day at 23:00'

sync_all_standings:
  cron: '0 7 * * *' 
  class: SyncAllStandingsWorker
  queue: low
  description: 'Sync standings for all active leagues at 7 am'

cache_warmup:
  cron: '*/5 * * * *'
  class: CacheWarmupWorker
  queue: low
  description: 'Warm up cache every 5 minutes'
